undo

diff --git a/foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config b/foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
--- a/foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
+++ b/foxbuntu/sysdrv/out/rootfs_uclibc_rv1106/usr/local/bin/femto-config
@@ -16,6 +16,23 @@ pause() {
   read -n 1 -s -r
 }
 
+# Dialog uses a different method to display colors, and is limited to only these 8.
+replace_colors() {
+  input="$1"
+  input="${input//$(echo -e '\033[0;30m')/\\Z0}"   # black
+  input="${input//$(echo -e '\033[0;31m')/\\Z1}"   # red
+  input="${input//$(echo -e '\033[0;32m')/\\Z2}"   # green
+  input="${input//$(echo -e '\033[0;33m')/\\Z3}"   # yellow
+  input="${input//$(echo -e '\033[0;34m')/\\Z4}"   # blue
+  input="${input//$(echo -e '\033[0;35m')/\\Z5}"   # magenta
+  input="${input//$(echo -e '\033[0;36m')/\\Z6}"   # cyan
+  input="${input//$(echo -e '\033[0;37m')/\\Z7}"   # white
+  input="${input//$(echo -e '\033[7m')/\\Zr}"      # invert
+  input="${input//$(echo -e '\033[4m')/\\Zu}"      # underline
+  input="${input//$(echo -e '\033[0m')/\\Zn}"      # reset
+  echo "$input"
+}
+
 loading() {
   dialog --no-collapse --infobox "$1" 5 45
 }
@@ -51,8 +68,8 @@ ingest_data() { # usage: `ingest_data "command.sh -argument" key_width`
   # Read the output from femto-meshtasticd-config.sh and store output_string
   while IFS=':' read -r key value; do
     # Trim leading/trailing spaces from key and value
-    key=$(femto-utils.sh -R "$(echo "$key" | xargs)")
-    value=$(femto-utils.sh -R "$(echo "$value" | xargs)")
+    key=$(replace_colors "$(echo "$key" | xargs)")
+    value=$(replace_colors "$(echo "$value" | xargs)")
     if [[ -z "$key" && -z "$value" ]]; then
       output_string+="---\n"
     else
@@ -153,7 +170,7 @@ networking_settings() {
       ;;
       7) # Test internet connection)
         loading "Testing internet connection..."
-        dialog --no-collapse --title "Internet connectivity test" --colors --msgbox "$(femto-utils.sh -R "$(femto-network-config.sh -t)")" 9 40
+        dialog --no-collapse --title "Internet connectivity test" --colors --msgbox "$(replace_colors "$(femto-network-config.sh -t)")" 9 40
       ;;
       8)
         return
@@ -174,12 +191,13 @@ utilities() {
       5 "Run USB configuration tool" "" \
       6 "Run OEM luckfox-config" "" \
       7 "Process viewer/manager" "" \
-      8 "Disable/enable logging" "" \
-      9 "Disable/enable activity LED" "" \
-      10 "Reboot" "" \
-      11 "Shutdown" "" \
+      8 "Disable/enable web terminal" "" \
+      9 "Disable/enable logging" "" \
+      10 "Disable/enable activity LED" "" \
+      11 "Reboot" "" \
+      12 "Shutdown" "" \
       " " "" "" \
-      12 "Back to main menu" "" 3>&1 1>&2 2>&3)
+      13 "Back to main menu" "" 3>&1 1>&2 2>&3)
     [ $? -eq 1 ] && break # Exit the loop if the user selects "Cancel" or closes the dialog
     
     case $utilities_choice in
@@ -270,11 +288,40 @@ $(ingest_data "femto-meshtasticd-config.sh -i" 15)" 0 0
       ;;
       6) luckfox-config ;;
       7) htop ;;
-      8) # logging)
+      8) 
+        choice=""   # zero the choice before loading the submenu
+        while true; do
+          echo "Checking web terminal status..."
+          ttyd_state=$(replace_colors "$(femto-utils.sh -t "check")")
+          [[ $ttyd_state == *"running"* ]] && ttyd_state+="\nWeb terminal available at \Zuhttps://$(hostname).local:7681\Zn"
+          choice=$(dialog --no-collapse --colors --title "Web Terminal" --cancel-label "Back" --help-button --default-item "$choice" --item-help --menu "Current state: $ttyd_state" 14 58 2 \
+            $(if ! echo "$ttyd_state" | grep -q 'enabled and running'; then echo "Enable and start (default) x  "; fi) \
+            $(if echo "$ttyd_state" | grep -q 'enabled'; then echo "Disable and stop x  "; fi) \
+            $(if echo "$ttyd_state" | grep -q 'enabled'; then echo "Start/restart ttyd service x  "; fi) \
+            $(if echo "$ttyd_state" | grep -q 'enabled'; then echo "View detailed service status x  "; fi) \
+            " " "" "" \
+            "Return to previous menu" "x" "" 3>&1 1>&2 2>&3)
+          exit_status=$? # This line checks the exit status of the dialog command
+          if [ $exit_status -eq 1 ]; then # Exit the loop if the user selects "Cancel" or closes the dialog
+            break
+          elif [ $exit_status -eq 2 ]; then # Help ("extra") button
+            dialog --no-collapse --colors --title "Web terminal help" --msgbox "Web terminal is a browser based terminal interface, and can be used as a replacement for an SSH client such as PuTTY.\nSSL encryption is provided by keys generated during first-boot. Your browser may give a warning (net::ERR_CERT_AUTHORITY_INVALID) about the self-signed encryption certificate. This is normal. In Chromium (Chrome, Edge) click \"Advanced\" and \"Continue to femtofox.local (unsafe)\".\n\nWeb terminal is provided by ttyd.\nLicense for ttyd: \`cat /opt/ttyd/license\`.\nFor more details, see: \Zuhttps://github.com/tsl0922/ttyd\Zn\n\nWeb terminal is enabled by default on Foxbuntu." 0 0
+          else
+            case $choice in
+              "Enable and start (default)") femto-utils.sh -t "enable" ;;
+              "Disable and stop") femto-utils.sh -t "disable" ;;
+              "Start/restart ttyd service") femto-utils.sh -t "start" ;;
+              "View detailed service status") dialog --no-collapse --title "ttyd service status" --msgbox "$(systemctl status ttyd)" 0 0 ;;
+              "Return to previous menu") break ;;
+            esac
+          fi
+        done
+      ;;
+      9) # logging)
         choice=""   # zero the choice before loading the submenu
         while true; do
           echo "Checking current logging status..."
-          choice=$(dialog --no-collapse --colors --title "Logging" --cancel-label "Back" --default-item "$choice" --item-help --menu "Before deploying a Femtofox, it is advisable to disable logging to reduce SD card wear.\nCurrent state: $(femto-utils.sh -R "$(femto-utils.sh -l "check")")" 14 50 2 \
+          choice=$(dialog --no-collapse --colors --title "Logging" --cancel-label "Back" --default-item "$choice" --item-help --menu "Before deploying a Femtofox, it is advisable to disable logging to reduce SD card wear.\nCurrent state: $(replace_colors "$(femto-utils.sh -l "check")")" 14 50 2 \
             1 "Enable (default)" "" \
             2 "Disable" "" \
             " " "" "" \
@@ -287,11 +334,11 @@ $(ingest_data "femto-meshtasticd-config.sh -i" 15)" 0 0
           esac
         done
       ;;
-      9) # activity LED)
+      10) # activity LED)
         choice=""   # zero the choice before loading the submenu
         while true; do
           echo "Checking current activity LED status..."
-          choice=$(dialog --no-collapse --colors --title "Logging" --cancel-label "Back" --default-item "$choice" --item-help --menu "Before deploying a Femtofox, it is advisable to disable the Activity LED to save power.\nCurrent state: $(femto-utils.sh -R "$(femto-utils.sh -a "check")")" 14 50 2 \
+          choice=$(dialog --no-collapse --colors --title "Logging" --cancel-label "Back" --default-item "$choice" --item-help --menu "Before deploying a Femtofox, it is advisable to disable the Activity LED to save power.\nCurrent state: $(replace_colors "$(femto-utils.sh -a "check")")" 14 50 2 \
             1 "Enable (default)" "" \
             2 "Disable" "" \
             " " "" "" \
@@ -304,21 +351,21 @@ $(ingest_data "femto-meshtasticd-config.sh -i" 15)" 0 0
           esac
         done
       ;;
-      10) # reboot)
+      11) # reboot)
         dialog --no-collapse --title "$title" --yesno "Reboot now?\n\nTip: Reboot can also be triggered by long-pressing the BOOT button on the luckfox." 10 45
         if [ $? -eq 0 ]; then #unless cancel/no
           loading "Rebooting..."
           femto-utils.sh -r
         fi
       ;;
-      11) # shutdown)
+      12) # shutdown)
         dialog --no-collapse --colors --title "$title" --yesno "Shut down now?\n\nTo power system back on, disconnect/reconnect power.\n\nThe system shutdown command prevents damage to the filesystem from power interrupts, but does not stop power consumption.\n\nTip: You can also shut down the Femtofox by pressing the BOOT button for 5 seconds or by running \`\Zusudo halt\Zn\`." 14 60
         if [ $? -eq 0 ]; then #unless cancel/no
           loading "Shutting down...\n\nPower consumption will not stop."
           femto-utils.sh -s
         fi
       ;;
-      12) return ;;
+      13) return ;;
     esac
   done
 }
@@ -329,18 +376,15 @@ set_lora_radio() {
   while true; do
     echo "Checking LoRa radio..."
     #Display filename, if exists: $(files=$(ls /etc/meshtasticd/config.d/* 2>/dev/null) && [ -n "$files" ] && echo "\n\nConfiguration files in use:\n$files" | paste -sd, -))
-    choice=$(dialog --no-collapse --colors --cancel-label "Cancel" --default-item "$choice" --title "Meshtastic LoRa radio" --item-help --menu "Currently configured LoRa radio:\n$(femto-utils.sh -R "$(femto-meshtasticd-config.sh -k)")$(ls -1 /etc/meshtasticd/config.d 2>/dev/null | paste -sd ', ' - | sed 's/^/ (/; s/$/)/; s/,/, /g' | grep -v '^ ()$')" 22 50 10 \
-       "Radio name:" "Configuration:" "" \
-       "" "" "" \
-       "Ebyte e22-900m30s" "(SX1262_TCXO)" "Included in Femtofox Pro" \
+    choice=$(dialog --no-collapse --colors --cancel-label "Cancel" --default-item "$choice" --title "Meshtastic LoRa radio" --item-help --menu "Currently configured LoRa radio:\n$(replace_colors "$(femto-meshtasticd-config.sh -k)")$(ls -1 /etc/meshtasticd/config.d 2>/dev/null | paste -sd ', ' - | sed 's/^/ (/; s/$/)/; s/,/, /g' | grep -v '^ ()$')" 19 50 10 \
+       "Ebyte e22-900m30s" "(SX1262_TCXO)" "" \
        "Ebyte e22-900m22s" "(SX1262_TCXO)" "" \
        "Ebyte e80-900m22s" "(SX1262_XTAL)" "" \
        "Heltec ht-ra62" "(SX1262_TCXO)" "" \
        "Seeed wio-sx1262" "(SX1262_TCXO)" "" \
-       "Waveshare sx126x-xxxm" "(SX1262_XTAL)" "Not recommended due issues with sending longer messages" \
+       "Waveshare sx126x-xxxm" "(SX1262_XTAL)" "" \
        "AI Thinker ra-01sh" "(SX1262_XTAL)" "" \
-       "LoRa Meshstick 1262" "(meshstick-1262)" "USB based LoRa radio from Mark Birss. https://github.com/markbirss/MESHSTICK" \
-       "Simulated radio" "(none)" "" \
+       "None" "(simulated radio)" "" \
       " " "" "" \
       "Skip" "" "" 3>&1 1>&2 2>&3)
     [ $? -eq 1 ] && break # Exit the loop if the user selects "Cancel" or closes the dialog
@@ -365,12 +409,9 @@ set_lora_radio() {
         radio="sx1262_xtal"
       ;;
       "AI Thinker ra-01sh")
-        radio="femto_sx1262_xtal"
+        radio="sx1262_xtal"
       ;;
-      "LoRa Meshstick 1262")
-        radio="lora-meshstick-1262"
-      ;;
-      "Simulated radio")
+      "None")
         radio="none"
       ;;
       "Skip")
@@ -388,7 +429,7 @@ legacy_admin() {
   choice=""   # zero the choice before loading the submenu
   while true; do
     loading "Getting current legacy admin state..."
-    choice=$(dialog --no-collapse --colors --title "Legacy Admin" --default-item "$choice" --help-button --item-help --menu "If the node you Femtofox needs to administer or be administered by is running 2.4.x or earlier, you should set this to Enabled.\n\nCurrent state: $(femto-utils.sh -R "$(femto-meshtasticd-config.sh -p)")" 16 65 5 \
+    choice=$(dialog --no-collapse --colors --title "Legacy Admin" --default-item "$choice" --help-button --item-help --menu "If the node you Femtofox needs to administer or be administered by is running 2.4.x or earlier, you should set this to Enabled.\n\nCurrent state: $(replace_colors "$(femto-meshtasticd-config.sh -p)")" 16 65 5 \
       1 "Enable" "" \
       2 "Disable (default)" "" \
       " " "" "" \
@@ -425,7 +466,7 @@ meshtastic_settings() {
   local title="Meshtastic Settings"
   while true; do
     echo "Checking Meshtasticd service state..."
-    meshtastic_choice=$(dialog --no-collapse --colors --title "$title" --cancel-label "Back" --default-item "$meshtastic_choice" --item-help --menu "Meshtasticd service is $(femto-utils.sh -R "$(femto-utils.sh -C "meshtasticd")")$(femto-meshtasticd-config.sh -k | grep -q 'simulated' && echo '\n\Z1Warning: using simulated radio\Zn')" 19 50 4 \
+    meshtastic_choice=$(dialog --no-collapse --colors --title "$title" --cancel-label "Back" --default-item "$meshtastic_choice" --item-help --menu "Meshtasticd service is $(replace_colors "$(femto-meshtasticd-config.sh -S)")$(femto-meshtasticd-config.sh -k | grep -q 'simulated' && echo '\n\Z1Warning: using simulated radio\Zn')" 19 50 4 \
       1 "View node info" "" \
       2 "View configuration URL & QR code" "" \
       3 "Set new configuration URL" "" \
@@ -539,14 +580,14 @@ meshtastic_settings() {
         dialog --no-collapse --title "Meshtastic Connectivity Test" --yesno "Will send \"test\" to channel 0 and wait for acknowledgement. Will try up to 3 times.\n\nPerform test?" 10 45
         if [ $? -eq 0 ]; then #unless cancel/no
           dialog --no-collapse --infobox "Performing mesh connectivity test.\n\nThis may take a while..." 6 45
-          dialog --no-collapse --colors --title "Meshtasticd connectivity test" --msgbox "$(femto-utils.sh -R "$(femto-meshtasticd-config.sh -w)")" 0 0
+          dialog --no-collapse --colors --title "Meshtasticd connectivity test" --msgbox "$(replace_colors "$(femto-meshtasticd-config.sh -w)")" 0 0
         fi
       ;;
       7) #manage meshtasticd service)
         choice=""   # zero the choice before loading the submenu
         while true; do
           echo "Checking Meshtasticd service state..."
-          local service_state="$(femto-utils.sh -R "$(femto-utils.sh -C "meshtasticd")")"
+          local service_state="$(replace_colors "$(femto-meshtasticd-config.sh -S)")"
           choice=$(dialog --no-collapse --colors --cancel-label "Back" --title "Meshtasticd Service" --default-item "$choice" --menu "Meshtasticd service is $service_state$(femto-meshtasticd-config.sh -k | grep -q 'simulated' && echo '\n\Z1Using simulated radio\Zn')" 17 52 5 \
             "View detailed service status" "x" \
             " " " " \
@@ -560,7 +601,7 @@ meshtastic_settings() {
           [ $? -eq 1 ] && break # Exit the loop if the user selects "Cancel" or closes the dialog
           case $choice in
             "View detailed service status") 
-              echo "Getting Meshtasticd service status..."
+              loading "Getting Meshtasticd service status..."
               dialog --no-collapse --title "Meshtasticd service status" --msgbox "$(systemctl status meshtasticd)" 0 0
             ;;
             "Start/restart service") 
@@ -647,7 +688,7 @@ help_menu() {
             5 "Back to Help Menu" "" 3>&1 1>&2 2>&3)
           [ $? -eq 1 ] && break # Exit the loop if the user selects "Cancel" or closes the dialog
           case $choice in
-            1) dialog --no-collapse --title "Femtofox" --msgbox "$(femto-pinout.sh -f)" 42 68 ;;
+            1) dialog --no-collapse --title "Femtofox" --msgbox "$(femto-pinout.sh -f)" 43 68 ;;
             2) dialog --no-collapse --title "Femtofox Zero" --msgbox "$(femto-pinout.sh -z)" 34 48 ;;
             3) dialog --no-collapse --title "Femtofox Tiny" --msgbox "$(femto-pinout.sh -t)" 38 70 ;;
             4) dialog --no-collapse --title "Luckfox Pico Mini" --msgbox "$(femto-pinout.sh -l)" 23 65 ;;
@@ -656,7 +697,7 @@ help_menu() {
         done
       ;;
       3) #Femtofox licensing info - short)
-        dialog --no-collapse --title "Femtofox license" --msgbox "$(femto-license.sh -f)" 31 65
+        dialog --no-collapse --title "Femtofox license" --msgbox "$(femto-license.sh -f)" 28 60
       ;;
       4) #Femtofox licensing info - long)
         clear
